# Generated by Django 4.2 on 2023-05-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0005_alter_jlsinvoi_invoi_id'),
        ('visitor', '0009_alter_jlsvisitors_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsParkings',
            fields=[
                ('pk_id', models.AutoField(db_comment='Unique parking ID', primary_key=True, serialize=False)),
                ('pk_lot', models.CharField(db_comment='Lot identifier', max_length=1)),
                ('pk_timein', models.DateTimeField(db_comment='Time into the lot of the current viehicle')),
                ('pk_timeout', models.DateTimeField(db_comment='Time get out of the current vehicle')),
                ('pk_fee', models.SmallIntegerField(db_comment='Parking fee during the parked time')),
                ('invoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.jlsinvoi')),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.jlsvisitors')),
            ],
            options={
                'db_table': 'jls_parkings',
            },
        ),
    ]
