# Generated by Django 4.2 on 2023-05-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsparkings',
            name='pk_fee',
            field=models.IntegerField(db_comment='Parking fee during the parked time', null=True),
        ),
    ]
