# Generated by Django 4.2 on 2023-05-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_jlsparkings_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsparkings',
            name='pk_lot',
            field=models.CharField(db_comment='Lot identifier', max_length=1, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='jlsparkings',
            name='pk_timein',
            field=models.DateTimeField(db_comment='Time into the lot of the current viehicle', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='jlsparkings',
            name='pk_timeout',
            field=models.DateTimeField(db_comment='Time get out of the current vehicle', verbose_name='To'),
        ),
    ]
