# Generated by Django 4.2 on 2023-05-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsPay',
            fields=[
                ('pay_id', models.IntegerField(db_comment='Unique payment ID for the payment', primary_key=True, serialize=False)),
                ('pay_method', models.CharField(db_comment='Payment method,CASH,CREDIT,DEBIT', max_length=8)),
                ('pay_date', models.DateTimeField(db_comment='Payment date of the current payment')),
                ('pay_amount', models.DecimalField(db_comment='Payment amount of the current payment', decimal_places=2, max_digits=3)),
                ('invoi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.jlsinvoi')),
            ],
            options={
                'db_table': 'jls_pay',
            },
        ),
    ]
