# Generated by Django 4.2 on 2023-05-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlspay',
            name='pay_id',
            field=models.AutoField(db_comment='Unique payment ID for the payment', primary_key=True, serialize=False),
        ),
    ]
