# Generated by Django 4.2 on 2023-05-11 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_jlspay_pay_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsCard',
            fields=[
                ('pay', models.OneToOneField(db_comment='Unique payment ID for the payment', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='payment.jlspay')),
                ('crd_fname', models.CharField(db_comment='card holder firstname.. ', max_length=10)),
                ('crd_lname', models.CharField(db_comment='Card holder lastname ', max_length=10)),
                ('crd_num', models.CharField(db_comment='Card number ', max_length=16)),
                ('crd_edate', models.DateField(db_comment='Experition date of the card ')),
                ('crd_cvv', models.CharField(db_comment='CVV of card', max_length=3)),
            ],
            options={
                'db_table': 'jls_card',
            },
        ),
        migrations.AlterField(
            model_name='jlspay',
            name='pay_amount',
            field=models.DecimalField(db_comment='Payment amount of the current payment', decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='jlspay',
            name='pay_date',
            field=models.DateField(db_comment='Payment date of the current payment'),
        ),
    ]
