# Generated by Django 4.2 on 2023-05-11 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_jlsinvoi_invoi_amount'),
        ('payment', '0003_jlscard_alter_jlspay_pay_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlspay',
            name='crd_cvv',
            field=models.CharField(db_comment='CVV of card', default='000', max_length=3, verbose_name='CVV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jlspay',
            name='crd_edate',
            field=models.DateField(db_comment='Experition date of the card ', default=django.utils.timezone.now, verbose_name='Expiration date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jlspay',
            name='crd_fname',
            field=models.CharField(db_comment='card holder firstname.. ', default='jerry', max_length=10, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jlspay',
            name='crd_lname',
            field=models.CharField(db_comment='Card holder lastname ', default='liu', max_length=10, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jlspay',
            name='crd_num',
            field=models.CharField(db_comment='Card number ', default='0000000000000000', max_length=16, verbose_name='Card number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jlspay',
            name='invoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.jlsinvoi'),
        ),
        migrations.DeleteModel(
            name='JlsCard',
        ),
    ]
