# Generated by Django 4.2 on 2023-05-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_jlspay_crd_cvv_jlspay_crd_edate_jlspay_crd_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsSummary',
            fields=[
                ('v_id', models.IntegerField(db_comment='Visitor ID. ', primary_key=True, serialize=False)),
                ('v_date', models.DateTimeField(db_comment='Visiting date. ')),
                ('amount', models.IntegerField(db_comment='amount.')),
                ('source', models.CharField(db_comment='source', max_length=10)),
                ('source_id', models.IntegerField(db_comment='source ID.')),
            ],
            options={
                'db_table': 'jls_summary',
                'unique_together': {('v_id', 'v_date')},
            },
        ),
    ]
