# Generated by Django 4.2 on 2023-05-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_jlssummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlssummary',
            name='v_date',
            field=models.DateField(db_comment='Visiting date. '),
        ),
    ]
