# Generated by Django 4.2 on 2023-05-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_jlssummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JlsSummary',
        ),
    ]
