# Generated by Django 4.2 on 2023-05-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_delete_jlssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsSummary',
            fields=[
                ('s_id', models.AutoField(db_comment='summary pk', primary_key=True, serialize=False)),
                ('v_id', models.IntegerField(db_comment='Visitor ID. ')),
                ('v_date', models.DateField(db_comment='Visiting date. ')),
                ('amount', models.IntegerField(db_comment='amount.')),
                ('source', models.CharField(db_comment='source', max_length=10)),
                ('source_id', models.IntegerField(db_comment='source ID.')),
            ],
            options={
                'db_table': 'jls_summary',
            },
        ),
    ]
