# Generated by Django 4.2 on 2023-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JlsAttractions',
            fields=[
                ('att_id', models.AutoField(db_comment='Unique Attration ID', primary_key=True, serialize=False)),
                ('att_name', models.CharField(db_comment='name of the attraction', max_length=20)),
                ('att_type', models.CharField(db_comment='Attraction type can be roller coaster, water ride, dark ride, kid ride etc. ', max_length=20)),
                ('att_descrip', models.CharField(db_comment='Attraction descriptions', max_length=300)),
                ('att_capacity', models.IntegerField(db_comment='Attraction capacity')),
                ('att_minhei', models.SmallIntegerField(db_comment='Minimum height requirement for the attraction in Centimeters. ')),
                ('att_duration', models.IntegerField(db_comment='Attraction duration, unit in MIN')),
                ('att_locsec', models.CharField(db_comment='Location section for the attraction', max_length=1)),
                ('att_status', models.CharField(db_comment='status can be closed, open, under mantainence', max_length=20)),
            ],
            options={
                'db_table': 'jls_attractions',
            },
        ),
    ]
