# Generated by Django 4.2 on 2023-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JlsShows',
            fields=[
                ('sh_id', models.SmallIntegerField(db_comment='Unique show ID', primary_key=True, serialize=False)),
                ('sh_name', models.CharField(db_comment='Show name', max_length=10)),
                ('sh_type', models.CharField(db_comment='Show type can be drama, musical, comedy, horror, adventure ', max_length=10)),
                ('sh_des', models.CharField(db_comment='Show description', max_length=30)),
                ('sh_stime', models.DateTimeField(db_comment='Starting time of the show')),
                ('sh_etime', models.DateTimeField(db_comment='Ending time of the show')),
                ('sh_wcacc', models.CharField(db_comment='If the show is wheelchair accessible', max_length=1)),
                ('sh_price', models.DecimalField(db_comment='Price for the show', decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'jls_shows',
            },
        ),
    ]
