# Generated by Django 4.2 on 2023-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_jlsshows_sh_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlsshows',
            name='sh_link',
            field=models.CharField(db_comment='link for the image', default='baidu.com', max_length=200),
        ),
    ]
