# Generated by Django 4.2 on 2023-05-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_jlsshows_sh_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlsshows',
            name='sh_link',
        ),
    ]
