# Generated by Django 4.2 on 2023-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_jlsshows_sh_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsshows',
            name='sh_des',
            field=models.CharField(db_comment='Show description', max_length=300),
        ),
        migrations.AlterField(
            model_name='jlsshows',
            name='sh_name',
            field=models.CharField(db_comment='Show name', max_length=30),
        ),
        migrations.AlterField(
            model_name='jlsshows',
            name='sh_type',
            field=models.CharField(db_comment='Show type can be drama, musical, comedy, horror, adventure ', max_length=30),
        ),
    ]
