# Generated by Django 4.2 on 2023-05-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_alter_jlsshows_sh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlsshows',
            name='sh_link',
            field=models.CharField(db_comment='link for the image', default='baidu.com', max_length=200),
        ),
    ]
