# Generated by Django 4.2 on 2023-05-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_jlsshows_sh_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsshows',
            name='sh_price',
            field=models.DecimalField(db_comment='Price for the show', decimal_places=2, max_digits=5),
        ),
    ]
