# Generated by Django 4.2 on 2023-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_jlsvsi_vsi_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsvsi',
            name='vsi_quant',
            field=models.DecimalField(db_comment='quantity of the shows', decimal_places=2, default=0, max_digits=5),
        ),
    ]
