# Generated by Django 4.2 on 2023-05-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_jlsvsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsvsi',
            name='vsi_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
