# Generated by Django 4.2 on 2023-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_alter_jlsvsi_vsi_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsvsi',
            name='vsi_quant',
            field=models.IntegerField(db_comment='quantity of the shows', default=0),
        ),
    ]
