# Generated by Django 4.2 on 2023-05-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_alter_jlsvsi_vsi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlsvsi',
            name='v',
        ),
    ]
