# Generated by Django 4.2 on 2023-05-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_remove_jlsvsi_v'),
    ]

    operations = [
    ]
