# Generated by Django 4.2 on 2023-05-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20230506_2232'),
    ]

    operations = [
    ]
