# Generated by Django 4.2 on 2023-05-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_jlsvsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlsvsi',
            name='vsi_quant',
            field=models.DecimalField(db_comment='quantity of item', decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
