# Generated by Django 4.2 on 2023-05-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_jlsvsi_vsi_quant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlsvsi',
            name='vsi_quant',
        ),
    ]
