# Generated by Django 4.2 on 2023-05-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlsinvoi',
            name='invoi_quant',
        ),
    ]
