# Generated by Django 4.2 on 2023-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_jlsinvoi_invoi_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlsinvoi',
            name='invoi_quant',
            field=models.DecimalField(db_comment='Amount for the invoice', decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
