# Generated by Django 4.2 on 2023-05-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_jlsinvoi_invoi_quant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlsinvoi',
            name='invoi_quant',
        ),
    ]
