# Generated by Django 4.2 on 2023-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_jlsinvoi_invoi_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsinvoi',
            name='invoi_id',
            field=models.AutoField(db_comment='Unique Invoice ID', primary_key=True, serialize=False),
        ),
    ]
