# Generated by Django 4.2 on 2023-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_jlsinvoi_invoi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsinvoi',
            name='invoi_amount',
            field=models.DecimalField(db_comment='Invoice amount (how much money). ', decimal_places=2, max_digits=6),
        ),
    ]
