# Generated by Django 4.2 on 2023-04-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsVisitors',
            fields=[
                ('v_id', models.AutoField(db_comment='Unique Visitor ID', primary_key=True, serialize=False)),
                ('v_fname', models.CharField(db_comment="Visitor's firstname", max_length=10, verbose_name='Firstname')),
                ('v_lname', models.CharField(db_comment="Visitor's lastname", max_length=10, verbose_name='Lastname')),
                ('v_state', models.CharField(db_comment="Visitor's state address", max_length=2, verbose_name='State')),
                ('v_city', models.CharField(db_comment="Visitor's city address", max_length=10, verbose_name='City')),
                ('v_staddr', models.CharField(db_comment="Visitor's street address", max_length=20, verbose_name='Street')),
                ('v_zip', models.CharField(db_comment="Visitor's zipcode. ", max_length=5, verbose_name='ZIP')),
                ('v_email', models.CharField(db_comment="Visitor's Email", max_length=30, verbose_name='Email')),
                ('v_phone', models.CharField(db_comment="Visitor's phone number", max_length=10, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jls_visitors',
            },
        ),
    ]
