# Generated by Django 4.2 on 2023-04-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JlsVisitors',
            fields=[
                ('v_id', models.AutoField(db_comment='Unique Visitor ID', primary_key=True, serialize=False)),
                ('v_fname', models.CharField(db_comment="Visitor's firstname", max_length=10)),
                ('v_lname', models.CharField(db_comment="Visitor's lastname", max_length=10)),
                ('v_state', models.CharField(db_comment="Visitor's state address", max_length=2)),
                ('v_city', models.CharField(db_comment="Visitor's city address", max_length=10)),
                ('v_staddr', models.CharField(db_comment="Visitor's street address", max_length=20)),
                ('v_zip', models.CharField(db_comment="Visitor's zipcode. ", max_length=5)),
                ('v_email', models.CharField(db_comment="Visitor's Email", max_length=30)),
                ('v_phone', models.CharField(db_comment="Visitor's phone number", max_length=10)),
                ('v_dob', models.DateTimeField(db_comment='date of birth of the visitor')),
                ('v_type', models.CharField(db_comment='Visitor type, can be "Group, Individual, Member or School". ', max_length=12)),
            ],
            options={
                'db_table': 'jls_visitors',
                'managed': False,
            },
        ),
    ]
