# Generated by Django 4.2 on 2023-05-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsMember',
            fields=[
                ('v', models.OneToOneField(db_comment='Unique Visitor ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='visitor.jlsvisitors')),
                ('mem_id', models.IntegerField(db_comment='Membership ID.')),
                ('mem_sdate', models.DateTimeField(db_comment='Membership start date. ')),
                ('mem_edate', models.DateTimeField(db_comment='Membership end date. ')),
            ],
            options={
                'db_table': 'jls_member',
            },
        ),
    ]
