# Generated by Django 4.2 on 2023-04-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlsvisitors',
            options={},
        ),
    ]
