# Generated by Django 4.2 on 2023-05-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_jlsmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlsvisitors',
            options={'managed': False},
        ),
    ]
