# Generated by Django 4.2 on 2023-05-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_jlsvisitors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlsvisitors',
            options={},
        ),
    ]
