# Generated by Django 4.2 on 2023-04-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_jlsvisitors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlsvisitors',
            name='v_dob',
        ),
        migrations.RemoveField(
            model_name='jlsvisitors',
            name='v_type',
        ),
    ]
