# Generated by Django 4.2 on 2023-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_jlsvisitors_v_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsmember',
            name='mem_edate',
            field=models.DateField(db_comment='Membership end date. '),
        ),
        migrations.AlterField(
            model_name='jlsmember',
            name='mem_sdate',
            field=models.DateField(db_comment='Membership start date. '),
        ),
    ]
