# Generated by Django 4.2 on 2023-05-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_jlsvisitors_v_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsGroup',
            fields=[
                ('v', models.OneToOneField(db_comment='Unique Visitor ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='visitor.jlsvisitors')),
                ('group_size', models.IntegerField(db_comment='Group size. ', default=0)),
            ],
            options={
                'db_table': 'jls_group',
            },
        ),
        migrations.AddField(
            model_name='jlsvisitors',
            name='v_group',
            field=models.CharField(db_comment='if user is in a group', default='N', max_length=1),
        ),
    ]
