# Generated by Django 4.2 on 2023-05-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0008_jlsgroup_jlsvisitors_v_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsvisitors',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
