# Generated by Django 4.2 on 2023-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_jlsstores_st_menu_item_jlsstores_st_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JlsStMenu',
            new_name='JlsMenu',
        ),
        migrations.AlterField(
            model_name='jlsstores',
            name='st_cat',
            field=models.CharField(db_comment='Store category. Category can be Food stall, Ice cream parlor, Restaurant, Gift Shop, Apparels ', max_length=30),
        ),
        migrations.AlterField(
            model_name='jlsstores',
            name='st_name',
            field=models.CharField(db_comment='Name of the store', max_length=40),
        ),
    ]
