# Generated by Django 4.2 on 2023-05-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_st_id_jlsmenu_id_alter_jlsmenu_it_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jlsmenu',
            old_name='id',
            new_name='store',
        ),
    ]
