# Generated by Django 4.2 on 2023-05-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_rename_id_jlsmenu_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JlsMenu',
            new_name='JlsItems',
        ),
        migrations.AlterModelTable(
            name='jlsitems',
            table='jls_items',
        ),
    ]
