# Generated by Django 4.2 on 2023-05-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_rename_jlsmenu_jlsitems_alter_jlsitems_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jlsitems',
            old_name='store',
            new_name='st',
        ),
    ]
