# Generated by Django 4.2 on 2023-05-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_rename_store_jlsitems_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsstores',
            name='st_cat',
            field=models.CharField(db_comment='Store category. Category can be Food stall, Ice cream parlor, Restaurant, Gift Shop, Apparels ', max_length=40),
        ),
        migrations.AlterField(
            model_name='jlsstores',
            name='st_name',
            field=models.CharField(db_comment='Name of the store', max_length=50),
        ),
    ]
