# Generated by Django 4.2 on 2023-05-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_jlsstores_st_cat_alter_jlsstores_st_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlsitems',
            options={'managed': True},
        ),
    ]
