# Generated by Django 4.2 on 2023-05-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_jlsinvoi_invoi_amount'),
        ('visitor', '0010_alter_jlsgroup_group_size'),
        ('stores', '0010_alter_jlsitems_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsOrder',
            fields=[
                ('order_id', models.BigIntegerField(db_comment='Order ID for store items.', primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(db_comment='Order date fore stores. ')),
                ('order_quant', models.SmallIntegerField(db_comment='Invoice quant for stores. ')),
                ('invoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.jlsinvoi')),
                ('it', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.jlsitems')),
                ('st', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.jlsstores')),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.jlsvisitors')),
            ],
            options={
                'db_table': 'jls_order',
                'managed': True,
            },
        ),
    ]
