# Generated by Django 4.2 on 2023-05-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_jlsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlsorder',
            name='order_id',
            field=models.AutoField(db_comment='Order ID for store items.', primary_key=True, serialize=False),
        ),
    ]
