# Generated by Django 4.2 on 2023-05-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_remove_jlsinvoi_invoi_quant'),
    ]

    operations = [
        migrations.CreateModel(
            name='JlsTickets',
            fields=[
                ('tk_id', models.IntegerField(db_comment='Unique ticket ID', primary_key=True, serialize=False)),
                ('tk_method', models.CharField(db_comment='Ticket method, online OL or onsite OS', max_length=2)),
                ('tk_purdate', models.DateTimeField(db_comment='Purchase date of the ticket')),
                ('tk_vdate', models.DateTimeField(db_comment='Visit date of the ticket')),
                ('tk_price', models.SmallIntegerField(db_comment='Ticket Price of the ticket')),
                ('tk_discount', models.IntegerField(db_comment='Percentage off of the ticket')),
                ('invoi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.jlsinvoi')),
            ],
            options={
                'db_table': 'jls_tickets',
            },
        ),
    ]
