# Generated by Django 4.2 on 2023-05-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_jlsvisitors_v_type'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlstickets',
            name='v',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.jlsvisitors'),
            preserve_default=False,
        ),
    ]
