# Generated by Django 4.2 on 2023-05-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_jlstickets_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlstickets',
            name='tk_id',
            field=models.AutoField(db_comment='Unique ticket ID', primary_key=True, serialize=False),
        ),
    ]
