# Generated by Django 4.2 on 2023-05-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_jlstickets_tk_purdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jlstickets',
            name='tk_discount',
            field=models.FloatField(db_comment='Percentage off of the ticket'),
        ),
    ]
