# Generated by Django 4.2 on 2023-05-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_jlstickets_invoi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlstickets',
            options={'managed': True},
        ),
    ]
