# Generated by Django 4.2 on 2023-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_jlstickets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlstickets',
            name='tk_dis2',
            field=models.FloatField(db_comment='Percentage off of the ticket', null=True),
        ),
    ]
