# Generated by Django 4.2 on 2023-05-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_jlsinvoi_invoi_date'),
        ('ticket', '0009_jlstickets_tk_dis2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jlstickets',
            name='tk_dis2',
        ),
        migrations.AlterField(
            model_name='jlstickets',
            name='invoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.jlsinvoi'),
        ),
    ]
