# Generated by Django 4.2 on 2023-05-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_jlsinvoi_invoi_date'),
        ('ticket', '0011_remove_jlstickets_invoi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlstickets',
            options={},
        ),
        migrations.AddField(
            model_name='jlstickets',
            name='invoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.jlsinvoi'),
        ),
    ]
