# Generated by Django 4.2 on 2023-05-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_jlsinvoi_invoi_date'),
        ('ticket', '0012_alter_jlstickets_options_jlstickets_invoi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jlstickets',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='jlstickets',
            name='invoi',
            field=models.ForeignKey(db_comment='wtf', null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.jlsinvoi'),
        ),
    ]
